apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-heimdall-conf
provisioner: example.com/external-nfs
parameters:
  server: NFS_SERVER_IP                  # < IP address of your NFS server
  path: HEIMDALL_CONF_NFS_PATH           # < NFS share path on the server
  readOnly: "false"
